// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// WARNING: This file contains placeholder values only!
// The actual app uses SecureFirebaseOptions from lib/core/config/secure_firebase_options.dart
// which loads credentials from config/firebase_config.json (excluded from git)
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB94zqobLiUfg-DpoZgkeaJ8IrG3NhUCdQ',
    appId: '1:1036541708035:web:b15c2d0d1758793f72cb36',
    messagingSenderId: '1036541708035',
    projectId: 'nalliq',
    authDomain: 'nalliq.firebaseapp.com',
    storageBucket: 'nalliq.firebasestorage.app',
    measurementId: 'G-7YXEZWSFZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nEV5xpE9fgK15ZMd411s03UAJR1RPoM',
    appId: '1:1036541708035:android:eba7983a7985ff9d72cb36',
    messagingSenderId: '1036541708035',
    projectId: 'nalliq',
    storageBucket: 'nalliq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTteY03WWc4vnUk0Dge_DiYrEWrvfS4pk',
    appId: '1:1036541708035:ios:757ee7d87142b64172cb36',
    messagingSenderId: '1036541708035',
    projectId: 'nalliq',
    storageBucket: 'nalliq.firebasestorage.app',
    iosBundleId: 'com.example.nalliq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTteY03WWc4vnUk0Dge_DiYrEWrvfS4pk',
    appId: '1:1036541708035:ios:757ee7d87142b64172cb36',
    messagingSenderId: '1036541708035',
    projectId: 'nalliq',
    storageBucket: 'nalliq.firebasestorage.app',
    iosBundleId: 'com.example.nalliq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB94zqobLiUfg-DpoZgkeaJ8IrG3NhUCdQ',
    appId: '1:1036541708035:web:8016fe08ca5c897472cb36',
    messagingSenderId: '1036541708035',
    projectId: 'nalliq',
    authDomain: 'nalliq.firebaseapp.com',
    storageBucket: 'nalliq.firebasestorage.app',
    measurementId: 'G-CCEE76X1CC',
  );

}